language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2 --use-mirrors; fi
  - pip install nose coverage python-coveralls "psutil>=1.2.0" --use-mirrors
  - pip install . --use-mirrors

script:
  - pip freeze
  - nosetests -s --verbose --with-coverage --cover-package=pyfarm.core tests

after_success:
  - coveralls
