language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

before_install:
  - curl https://raw.githubusercontent.com/pyfarm/pyfarm/master/misc/retry.sh -o retry.sh

install:
  - source retry.sh
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then retry pip install unittest2; fi
  - retry pip install nose coverage python-coveralls "psutil>=1.2.0"
  - retry pip install .

script:
  - pip freeze
  - nosetests -s --verbose --with-coverage --cover-package=pyfarm.core tests

after_success:
  - coveralls
